name: Ejecucion CD-DEV

on:
  push:
    branches: ["main"]

jobs:
  build:
    # env:
    #   NODE_OPTIONS: "--max-old-space-size=4096"
    runs-on: windows-latest
    outputs:
      tag: 23

    steps:
      - name: GitHub checkout
        uses: actions/checkout@v3


      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.17.1"

      - name: Install Angular CLI
        run: npm install -g @angular/cli@12.2.16

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Set NODE_OPTIONS to increase max-old-space-size
        run: echo NODE_OPTIONS=--max-old-space-size=8076 >> $GITHUB_ENV


      - name: Check if can run a project
        run: node -e "console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))"
          
      - name: make a dir in root directory
        run: ls

      - name: execute field
        run: cd.. && ls




      - name: Build with Maven
        run: |
          pwd
          ls
          cd Codigo
          mvn clean package -Pdev  -DskipTests
